name: 😃 Notification

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        curl --header "Content-Type: application/json" -d '{"content": "Un nou push"}' $DISCORD_WEBHOOK_URL