name: 😃 Notification

on:
  push:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      run: |
        curl -X POST ${{ secrets.DISCORD_WEBHOOK }} --header -d "Un nou push"