name: 😃 Notification

on:
  push:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      run: |
        curl --header "Content-Type: application/json" -d "{"content": "Un nou push"}"  ${{ secrets.DISCORD_WEBHOOK }}